config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks, except: [:show]

  root 'home#land'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  title      :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Task < ActiveRecord::Base
  module Status
    NOT_STARTED = 0
    IN_PROGRESS = 1
    FINISHED = 2
  end

  belongs_to :user
  
validates :title,presence: true,uniqueness:true

  def not_started?
    self.status ==
    Status::NOT_STARTED
  end

  def in_progress?
    self.status ==
    Status::IN_PROGRESS
  end

  def finished?
    self.status ==
    Status::FINISHED
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def land
  end
end

app/controllers/tasks_controller.rb
 # == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  title      :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @not_started_tasks = current_user.tasks.where(status:
     Task::Status::NOT_STARTED)
    @in_progress_tasks = current_user.tasks.where(status:
      Task::Status::IN_PROGRESS)
    @finished_tasks = current_user.tasks.where(status:
       Task::Status::FINISHED)
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @task.update_attribute(:status,
    params[:status].to_i)
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

private
  def task_params
    params.require(:task).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages_tags
    messages = ""
    flash.each do |type,msg|
      type = "success" if type == "notice"
      type = "danger" if type == "error"

      messages += (content_tag(:div,class:"alert alert-#{type} alert-dismissible",role:"alert")do
        content_tag(:button,class: "close", data:{dismiss: "alert"},"aria-label" => "Close") do
          content_tag(:span,raw("&times;"),"aria-hidden" => "true")
        end + msg
      end )
    end

    return raw(messages)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  title      :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module TasksHelper
end

app/views/home/land.html.erb
<div id="land">
  <div class="vcenter">
    <h1>Track.It.</h1>
    <%= link_to "Login", tasks_path,id: "login-trigger",class:"btn"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trackit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,200,300,500,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    (Logged in as: <%= current_user.email %>)
<%else %>
  <%= link_to "Login",new_user_session_path %>
<% end %>
<%= flash_messages_tags %>
<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<li id= "<%= dom_id(task) %>">
  <%= task.title %>
  (
  <%= link_to("Start", task_path(task,status:
  Task::Status::IN_PROGRESS), method: :patch,remote: true) if
  task.not_started? %>

  <%= link_to("Finish", task_path(task,status:
  Task::Status::FINISHED), method:
  :patch,remote: true) if task.in_progress? %>
<%= content_tag(:span, "|") if task.in_progress?
%>
  <%= link_to("Shelf", task_path(task,status:
  Task::Status::NOT_STARTED), method:
  :patch,remote: true) if task.in_progress? || task.finished? %>


  )
</li>

app/views/tasks/index.html.erb
<%= link_to "Add New Task", new_task_path, class:
"btn btn-primary btn-sm pull-right" %>
<h1>Tasks</h1>



<h2>Not Started</h2>
<ul id = "tasks_<%= Task::Status::NOT_STARTED %>">
  <%= render @not_started_tasks %>
</ul>

<h2>In Progress</h2>
<ul id = "tasks_<%= Task::Status::IN_PROGRESS %>">
  <%= render @in_progress_tasks %>
</ul>

<h2>Finished</h2>
<ul id = "tasks_<%= Task::Status::FINISHED %>">
  <%= render @finished_tasks %>
</ul>

app/views/tasks/new.html.erb
<h1>Add New Task</h1>
<%= simple_form_for @task do |f| %>
  <%= f.input :title, placeholder: "What do you want to do today?" %>
  <%= f.submit "Add Task", class: "btn btn-primary" %>
<% end %>

app/views/tasks/update.js.erb
$('li#<%= dom_id(@task) %>').remove();
$('ul#tasks_<%= @task.status %>').append('<%= escape_javascript render(@task) %>')